"use client";
import { useEffect, useState } from "react";

type Any = Record<string, any>;
const defaults = { platform_name: "Business Suite Platform Settings", owner_company: "Business Suite", platform_logo: "", website_logo: "", support_email: "", default_country: "South Africa", default_currency: "ZAR", default_trial_days: 14, billing_reminder_days: 7, payfast_merchant_id: "", payfast_merchant_key: "", payfast_passphrase: "", payfast_sandbox: 1, payfast_return_url: "", payfast_cancel_url: "", payfast_notify_url: "" };
function Input({ label, value, onChange, type = "text", placeholder }: { label: string; value: any; onChange: (v: any) => void; type?: string; placeholder?: string }) { return <label className="field"><span>{label}</span><input className="inp" type={type} value={value ?? ""} placeholder={placeholder || label} onChange={(e) => onChange(type === "number" ? Number(e.currentTarget.value) : e.currentTarget.value)} /></label>; }

export default function AdminPlatformSettings() {
  const [settings, setSettings] = useState<Any>(defaults);
  const [msg, setMsg] = useState("");
  const [loading, setLoading] = useState(false);
  useEffect(() => { (async () => { setLoading(true); try { const res = await fetch("/api/settings/platform-control", { cache: "no-store" }); const json = await res.json(); if (!res.ok) throw new Error(json.error || "Could not load platform settings"); setSettings({ ...defaults, ...(json.data || {}) }); } catch (e) { setMsg(e instanceof Error ? e.message : "Could not load platform settings"); } finally { setLoading(false); } })(); }, []);
  async function save() { setLoading(true); setMsg(""); try { const res = await fetch("/api/settings/platform-control", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const json = await res.json(); if (!res.ok) throw new Error(json.error || "Could not save platform settings"); setSettings({ ...defaults, ...(json.data || settings) }); setMsg("Platform settings saved. These settings now control website branding, owner branding, PayFast billing and defaults."); } catch (e) { setMsg(e instanceof Error ? e.message : "Could not save platform settings"); } finally { setLoading(false); } }
  async function upload(file: File | undefined | null, target: "platform" | "website") { if (!file) return; setLoading(true); setMsg(""); try { const fd = new FormData(); fd.set("file", file); fd.set("target", target); const res = await fetch("/api/settings/upload-logo", { method: "POST", body: fd }); const json = await res.json(); if (!res.ok) throw new Error(json.error || "Logo upload failed"); setSettings((p) => ({ ...p, [target === "platform" ? "platform_logo" : "website_logo"]: json.data?.file_url || "" })); setMsg("Logo uploaded. Save platform settings to apply it everywhere."); } catch (e) { setMsg(e instanceof Error ? e.message : "Logo upload failed"); } finally { setLoading(false); } }
  return <div className="card card-pad" style={{ marginTop: 18 }}>
    <div className="page-head" style={{ padding: 0, marginBottom: 18 }}><div><h3 style={{ margin: 0 }}>SaaS Admin Control Settings</h3><div className="page-sub">Owner branding, website logo, South African defaults, trial rules and PayFast subscription billing.</div></div><button className="btn btn-primary" disabled={loading} onClick={save}>{loading ? "Saving..." : "Save admin settings"}</button></div>
    <div className="two-col" style={{ alignItems: "start" }}><div><h4>Platform Branding</h4><Input label="Platform Name" value={settings.platform_name} onChange={(v) => setSettings({ ...settings, platform_name: v })} /><Input label="Owner Company" value={settings.owner_company} onChange={(v) => setSettings({ ...settings, owner_company: v })} /><Input label="Support Email" value={settings.support_email} onChange={(v) => setSettings({ ...settings, support_email: v })} /><div className="field-row"><label className="field"><span>Business Suite / Owner Logo</span><input className="inp" type="file" accept="image/*" onChange={(e) => upload(e.target.files?.[0], "platform")} /></label><label className="field"><span>Website Logo</span><input className="inp" type="file" accept="image/*" onChange={(e) => upload(e.target.files?.[0], "website")} /></label></div></div><div><h4>Defaults</h4><div className="field-row"><Input label="Default Currency" value={settings.default_currency} onChange={(v) => setSettings({ ...settings, default_currency: v || "ZAR" })} /><Input label="Default Country" value={settings.default_country} onChange={(v) => setSettings({ ...settings, default_country: v || "South Africa" })} /></div><div className="field-row"><Input label="Trial Days" type="number" value={settings.default_trial_days} onChange={(v) => setSettings({ ...settings, default_trial_days: v })} /><Input label="Billing Reminder Days" type="number" value={settings.billing_reminder_days} onChange={(v) => setSettings({ ...settings, billing_reminder_days: v })} /></div><label className="field"><span>PayFast Mode</span><select className="inp" value={String(settings.payfast_sandbox ? 1 : 0)} onChange={(e) => setSettings({ ...settings, payfast_sandbox: e.target.value === "1" ? 1 : 0 })}><option value="1">Sandbox</option><option value="0">Live</option></select></label></div></div>
    <div className="two-col" style={{ alignItems: "start", marginTop: 18 }}><div><h4>PayFast Merchant Settings</h4><Input label="Merchant ID" value={settings.payfast_merchant_id} onChange={(v) => setSettings({ ...settings, payfast_merchant_id: v })} /><Input label="Merchant Key" type="password" value={settings.payfast_merchant_key} onChange={(v) => setSettings({ ...settings, payfast_merchant_key: v })} /><Input label="Passphrase" type="password" value={settings.payfast_passphrase} onChange={(v) => setSettings({ ...settings, payfast_passphrase: v })} /></div><div><h4>PayFast URLs</h4><Input label="Return URL" value={settings.payfast_return_url} onChange={(v) => setSettings({ ...settings, payfast_return_url: v })} /><Input label="Cancel URL" value={settings.payfast_cancel_url} onChange={(v) => setSettings({ ...settings, payfast_cancel_url: v })} /><Input label="Notify / ITN URL" value={settings.payfast_notify_url} onChange={(v) => setSettings({ ...settings, payfast_notify_url: v })} /></div></div>
    <div className="banner info" style={{ marginTop: 16 }}>Trial expiry and billing reminder emails use these admin settings plus each tenant’s trial end, next billing date and payment link.</div>
    {msg && <div className={msg.toLowerCase().includes("could") || msg.toLowerCase().includes("failed") ? "banner" : "banner info"} style={{ marginTop: 18 }}>{msg}</div>}
  </div>;
}
