import { NextResponse } from 'next/server'
import { getCrudConfig, toERPDoc } from '@/lib/crudConfig'
import { erpDelete, erpGet, erpPatch, erpMethod, BusinessSuiteError } from '@/lib/server/erpnext'
import { getModuleMeta, sanitizeDocFromMeta } from '@/lib/server/doctypeMeta'
const itemModules = new Set(['quotes', 'sales-orders', 'invoices', 'purchase-orders'])
export async function GET(_req: Request,{ params }: { params: { module: string; id: string } }) { try { const config = getCrudConfig(params.module); if (!config) return NextResponse.json({ error: 'Unknown module' }, { status: 404 }); const data = await erpGet(`/api/resource/${encodeURIComponent(config.doctype)}/${encodeURIComponent(params.id)}`); return NextResponse.json({ data: (data as any).data || (data as any).message || data }) } catch (e) { return NextResponse.json({ error: e instanceof Error ? e.message : 'Could not load record' }, { status: e instanceof BusinessSuiteError ? e.status : 500 }) } }
export async function PUT(req: Request,{ params }: { params: { module: string; id: string } }) { try { const config = getCrudConfig(params.module); if (!config) return NextResponse.json({ error: 'Unknown module' }, { status: 404 }); const body = await req.json(); const meta = await getModuleMeta(config); const metadataDoc = sanitizeDocFromMeta(body, meta); const legacyDoc = toERPDoc(params.module, body); const doc = itemModules.has(params.module) ? { ...metadataDoc, ...legacyDoc } : { ...legacyDoc, ...metadataDoc }; const updated = await erpPatch(config.doctype, params.id, doc); return NextResponse.json({ data: updated }) } catch (e) { return NextResponse.json({ error: e instanceof Error ? e.message : 'Could not update record' }, { status: e instanceof BusinessSuiteError ? e.status : 500 }) } }
export async function PATCH(req: Request,{ params }: { params: { module: string; id: string } }) { try { const config = getCrudConfig(params.module); if (!config) return NextResponse.json({ error: 'Unknown module' }, { status: 404 }); const body = await req.json(); if (body.action === 'submit' || body.action === 'cancel') { const result = await erpMethod('fuze_suite.api.business_crud.submit_or_cancel', { doctype: config.doctype, name: params.id, action: body.action }); return NextResponse.json({ data: result }) } return NextResponse.json({ error: 'Unsupported action' }, { status: 400 }) } catch (e) { return NextResponse.json({ error: e instanceof Error ? e.message : 'Could not perform action' }, { status: e instanceof BusinessSuiteError ? e.status : 500 }) } }
export async function DELETE(_req: Request,{ params }: { params: { module: string; id: string } }) { try { const config = getCrudConfig(params.module); if (!config) return NextResponse.json({ error: 'Unknown module' }, { status: 404 }); await erpDelete(config.doctype, params.id); return NextResponse.json({ ok: true }) } catch (e) { return NextResponse.json({ error: e instanceof Error ? e.message : 'Could not delete record' }, { status: e instanceof BusinessSuiteError ? e.status : 500 }) } }
