"use client";
import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import StatusChip from "@/components/StatusChip";

type Any = Record<string, any>;
const money = (v?: number) => `R ${Number(v || 0).toLocaleString("en-ZA", { maximumFractionDigits: 0 })}`;
const dateOnly = (v?: string) => (v ? String(v).slice(0, 10) : "—");
function Card({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <div className="card"><div className="card-head"><h3>{title}</h3>{action}</div><div className="card-body">{children}</div></div>; }
function K({ label, value, hint, tone = "" }: { label: string; value: string; hint?: string; tone?: string }) { return <div className={`kpi ${tone}`}><div className="label">{label}</div><div className="val">{value}</div><div className="hint">{hint}</div></div>; }
function Empty({ label }: { label: string }) { return <div className="empty">{label}</div>; }

const emptyDashboard = { kpis: { revenue:0, expenses:0, profit:0, cashBalance:0, receivables:0, payables:0, cashIn:0, cashOut:0 }, monthly: [] as Any[], aging: ["Current","1-30","31-60","61-90","90+"].map(bucket=>({ bucket, receivable:0, payable:0 })), overdueInvoices: [] as Any[] };
const emptyVat = { outputVat:0, inputVat:0, netVat:0, standardRate:15, monthly: [] as Any[], returns: [] as Any[], byStatus: {} as Any, latest: null as unknown as Any };
const emptyBank = { bankAccounts: [] as Any[], unreconciledPayments: [] as Any[], totals: { unreconciledCount:0, unreconciledAmount:0 } };
const emptyPayroll = { salarySlips: [] as Any[], totals: { employees:0, gross:0, deductions:0, net:0 } };
async function getJson(url: string) { try { const r = await fetch(url, { cache: "no-store" }); const j = await r.json().catch(()=>null); return r.ok && j && !j.error ? j : null; } catch { return null; } }

export default function FinanceDashboardClient() {
  const [tab, setTab] = useState("overview");
  const [dashboard, setDashboard] = useState<Any>(emptyDashboard);
  const [vat, setVat] = useState<Any>(emptyVat);
  const [bank, setBank] = useState<Any>(emptyBank);
  const [payroll, setPayroll] = useState<Any>(emptyPayroll);
  const [audit, setAudit] = useState<Any[]>([]);
  const [report, setReport] = useState<Any | null>(null);
  const [loading, setLoading] = useState(true);
  const [warning, setWarning] = useState("");

  useEffect(() => { let alive = true; (async()=>{
    setLoading(true);
    const [d,v,b,p,a] = await Promise.all([getJson("/api/finance/dashboard"),getJson("/api/finance/vat"),getJson("/api/finance/bank-reconciliation"),getJson("/api/finance/payroll"),getJson("/api/finance/audit")]);
    if (!alive) return;
    setDashboard({ ...emptyDashboard, ...(d || {}), kpis: { ...emptyDashboard.kpis, ...(d?.kpis || {}) }, monthly: Array.isArray(d?.monthly)?d.monthly:[], aging: Array.isArray(d?.aging)?d.aging:emptyDashboard.aging, overdueInvoices: Array.isArray(d?.overdueInvoices)?d.overdueInvoices:[] });
    setVat({ ...emptyVat, ...(v || {}), monthly: Array.isArray(v?.monthly)?v.monthly:[], returns: Array.isArray(v?.returns)?v.returns:[] });
    setBank({ ...emptyBank, ...(b || {}), bankAccounts: Array.isArray(b?.bankAccounts)?b.bankAccounts:[], unreconciledPayments: Array.isArray(b?.unreconciledPayments)?b.unreconciledPayments:[], totals: { ...emptyBank.totals, ...(b?.totals || {}) } });
    setPayroll({ ...emptyPayroll, ...(p || {}), salarySlips: Array.isArray(p?.salarySlips)?p.salarySlips:[], totals: { ...emptyPayroll.totals, ...(p?.totals || {}) } });
    setAudit(Array.isArray(a)?a:[]);
    setWarning(d ? "" : "Finance data is not fully available yet. Check accounting setup, permissions, or missing records.");
    setLoading(false);
  })(); return ()=>{ alive = false; }; }, []);

  async function runReport(report_name: string) { try { const res = await fetch("/api/finance/report", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ report_name, filters: {} }) }); setReport(await res.json().catch(()=>({ error:"Could not run report" }))); } catch(e) { setReport({ error: e instanceof Error ? e.message : "Could not run report" }); } setTab("reports"); }
  const reportRows = useMemo(() => { const rows = report?.result || report?.message?.result || []; return Array.isArray(rows) ? rows.slice(0, 40) : []; }, [report]);
  const k = { ...emptyDashboard.kpis, ...(dashboard?.kpis || {}) }, monthly = Array.isArray(dashboard?.monthly)?dashboard.monthly:[], aging = Array.isArray(dashboard?.aging)?dashboard.aging:emptyDashboard.aging, overdueInvoices = Array.isArray(dashboard?.overdueInvoices)?dashboard.overdueInvoices:[];
  const vatMonthly = Array.isArray(vat?.monthly)?vat.monthly:[], vatReturns = Array.isArray(vat?.returns)?vat.returns:[], bankAccounts = Array.isArray(bank?.bankAccounts)?bank.bankAccounts:[], bankTotals = { ...emptyBank.totals, ...(bank?.totals || {}) }, unreconciledPayments = Array.isArray(bank?.unreconciledPayments)?bank.unreconciledPayments:[];
  const payrollTotals = { ...emptyPayroll.totals, ...(payroll?.totals || {}) }, salarySlips = Array.isArray(payroll?.salarySlips)?payroll.salarySlips:[];

  return <div>
    <div className="page-head"><div><h1 className="page-title">Financial Dashboard</h1><div className="page-sub">Accounting, VAT, cashflow, bank reconciliation, payroll, reports and audit trail.</div></div><div className="row"><button className="btn" onClick={()=>runReport("Profit and Loss Statement")}>Run P&L</button><button className="btn" onClick={()=>runReport("Balance Sheet")}>Balance Sheet</button><button className="btn btn-primary" onClick={()=>runReport("Cash Flow")}>Cash Flow</button></div></div>
    {loading && <div className="card card-pad"><Empty label="Loading financial dashboard…" /></div>}
    {!loading && warning && <div className="notice warn">{warning}</div>}
    <div className="pill-nav">{["overview","vat","bank","payroll","reports","audit"].map(t=><button key={t} className={tab===t?"on":""} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>
    {tab === "overview" && <><div className="kpi-grid"><K label="Revenue" value={money(k.revenue)} hint="Sales invoices" tone="teal"/><K label="Expenses" value={money(k.expenses)} hint="Purchase invoices" tone="warn"/><K label="Profit" value={money(k.profit)} hint="Revenue minus expenses" tone={k.profit >= 0 ? "teal" : "warn"}/><K label="Cash Position" value={money(k.cashBalance)} hint="Cash in minus cash out" tone="purple"/></div><div className="kpi-grid"><K label="Receivables" value={money(k.receivables)} hint="Customer outstanding"/><K label="Payables" value={money(k.payables)} hint="Supplier outstanding"/><K label="Cash In" value={money(k.cashIn)} hint="Received payments" tone="teal"/><K label="Cash Out" value={money(k.cashOut)} hint="Outgoing payments" tone="warn"/></div><div className="two-col"><Card title="Profit & Loss Trend"><div style={{height:280}}><ResponsiveContainer width="100%" height="100%"><BarChart data={monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis tickFormatter={(v)=>`R${Number(v)/1000}k`}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Legend/><Bar dataKey="income" name="Income" fill="var(--teal)"/><Bar dataKey="expense" name="Expense" fill="var(--warn)"/></BarChart></ResponsiveContainer></div></Card><Card title="Cashflow"><div style={{height:280}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis tickFormatter={(v)=>`R${Number(v)/1000}k`}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Legend/><Area type="monotone" dataKey="cashIn" name="Cash In" stroke="var(--teal)" fill="var(--teal)" fillOpacity={0.18}/><Area type="monotone" dataKey="cashOut" name="Cash Out" stroke="var(--danger)" fill="var(--danger)" fillOpacity={0.12}/></AreaChart></ResponsiveContainer></div></Card></div><div className="two-col mt"><Card title="AR / AP Aging"><div style={{height:260}}><ResponsiveContainer width="100%" height="100%"><BarChart data={aging}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="bucket"/><YAxis tickFormatter={(v)=>`R${Number(v)/1000}k`}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Legend/><Bar dataKey="receivable" name="Receivables" fill="var(--blue)"/><Bar dataKey="payable" name="Payables" fill="var(--warn)"/></BarChart></ResponsiveContainer></div></Card><Card title="Overdue Customer Invoices"><table className="data"><thead><tr><th>Invoice</th><th>Customer</th><th>Due</th><th>Outstanding</th><th>Status</th></tr></thead><tbody>{overdueInvoices.map((inv:Any)=><tr key={inv.name}><td>{inv.name}</td><td>{inv.customer}</td><td>{dateOnly(inv.due_date)}</td><td>{money(inv.outstanding_amount)}</td><td><StatusChip status={inv.status}/></td></tr>)}{overdueInvoices.length===0&&<tr><td colSpan={5}><Empty label="No overdue invoices."/></td></tr>}</tbody></table></Card></div></>}
    {tab === "vat" && <><div className="kpi-grid"><K label="Output VAT" value={money(vat.outputVat)} hint="Fuze VAT Return output_vat"/><K label="Input VAT" value={money(vat.inputVat)} hint="Fuze VAT Return input_vat"/><K label="Net VAT" value={money(vat.netVat)} hint="Payable / refundable" tone={vat.netVat >= 0 ? "warn" : "teal"}/><K label="VAT Returns" value={String(vatReturns.length)} hint="Fuze VAT Return records"/></div><Card title="VAT Movement"><div style={{height:300}}><ResponsiveContainer width="100%" height="100%"><LineChart data={vatMonthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis tickFormatter={(v)=>`R${Number(v)/1000}k`}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Legend/><Line dataKey="vatOutput" name="Output VAT" stroke="var(--warn)" strokeWidth={2}/><Line dataKey="vatInput" name="Input VAT" stroke="var(--teal)" strokeWidth={2}/><Line dataKey="netVat" name="Net VAT" stroke="var(--navy)" strokeWidth={2}/></LineChart></ResponsiveContainer></div></Card><Card title="Recent VAT Returns"><table className="data"><thead><tr><th>Return</th><th>Company</th><th>Period</th><th>Status</th><th>Output</th><th>Input</th><th>Net</th></tr></thead><tbody>{vatReturns.slice(0,30).map((r:Any)=><tr key={r.name}><td>{r.name}</td><td>{r.company}</td><td>{dateOnly(r.from_date)} → {dateOnly(r.to_date)}</td><td><StatusChip status={r.status}/></td><td>{money(r.output_vat)}</td><td>{money(r.input_vat)}</td><td>{money(r.net_vat)}</td></tr>)}{vatReturns.length===0&&<tr><td colSpan={7}><Empty label="No Fuze VAT Return records found."/></td></tr>}</tbody></table></Card></>}
    {tab === "bank" && <><div className="kpi-grid"><K label="Bank Accounts" value={String(bankAccounts.length)} hint="Bank ledgers"/><K label="Unreconciled" value={String(bankTotals.unreconciledCount)} hint="Payments and journals" tone="warn"/><K label="Variance Amount" value={money(bankTotals.unreconciledAmount)} hint="Needs matching"/><K label="Status" value={bankTotals.unreconciledCount ? "Action Needed" : "Clean"} hint="Reconciliation control" tone={bankTotals.unreconciledCount ? "warn" : "teal"}/></div><Card title="Unreconciled Payments"><table className="data"><thead><tr><th>Payment</th><th>Date</th><th>Type</th><th>Party</th><th>Amount</th><th>Ref</th></tr></thead><tbody>{unreconciledPayments.slice(0,30).map((p:Any)=><tr key={p.name}><td>{p.name}</td><td>{dateOnly(p.posting_date)}</td><td>{p.payment_type}</td><td>{p.party}</td><td>{money(p.paid_amount)}</td><td>{p.reference_no || "—"}</td></tr>)}{unreconciledPayments.length===0&&<tr><td colSpan={6}><Empty label="No unreconciled payments."/></td></tr>}</tbody></table></Card></>}
    {tab === "payroll" && <><div className="kpi-grid"><K label="Employees" value={String(payrollTotals.employees)} hint="Active payroll records"/><K label="Gross Pay" value={money(payrollTotals.gross)} hint="Salary slips"/><K label="Deductions" value={money(payrollTotals.deductions)} hint="PAYE/UIF/other" tone="warn"/><K label="Net Pay" value={money(payrollTotals.net)} hint="Employee payout" tone="teal"/></div><Card title="Latest Salary Slips"><table className="data"><thead><tr><th>Slip</th><th>Employee</th><th>Period</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Status</th></tr></thead><tbody>{salarySlips.slice(0,30).map((s:Any)=><tr key={s.name}><td>{s.name}</td><td>{s.employee_name || s.employee}</td><td>{dateOnly(s.start_date)} → {dateOnly(s.end_date)}</td><td>{money(s.gross_pay)}</td><td>{money(s.total_deduction)}</td><td>{money(s.net_pay)}</td><td><StatusChip status={s.status || (s.docstatus===1 ? "Submitted" : "Draft")}/></td></tr>)}{salarySlips.length===0&&<tr><td colSpan={7}><Empty label="No salary slips found."/></td></tr>}</tbody></table></Card></>}
    {tab === "reports" && <Card title="Financial Report Result" action={<div className="row"><button className="btn btn-sm" onClick={()=>runReport("Profit and Loss Statement")}>P&L</button><button className="btn btn-sm" onClick={()=>runReport("Balance Sheet")}>Balance Sheet</button><button className="btn btn-sm" onClick={()=>runReport("Cash Flow")}>Cash Flow</button></div>}>{report?.error ? <Empty label={String(report.error)}/> : !report ? <Empty label="Choose a report above to run live."/> : <table className="data"><tbody>{reportRows.map((row:any,idx:number)=><tr key={idx}>{(Array.isArray(row)?row:Object.values(row)).slice(0,8).map((cell:any,i:number)=><td key={i}>{typeof cell === "number" ? money(cell) : String(cell ?? "—")}</td>)}</tr>)}{reportRows.length===0&&<tr><td><Empty label="No report rows returned."/></td></tr>}</tbody></table>}</Card>}
    {tab === "audit" && <Card title="Audit Trail"><table className="data"><thead><tr><th>Date</th><th>User</th><th>Action</th><th>DocType</th><th>Document</th><th>Details</th></tr></thead><tbody>{audit.slice(0,80).map((r:Any)=><tr key={r.name}><td>{dateOnly(r.timestamp || r.modified)}</td><td>{r.user}</td><td>{r.action}</td><td>{r.reference_doctype}</td><td>{r.reference_name}</td><td style={{maxWidth:520,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{r.details || "—"}</td></tr>)}{audit.length===0&&<tr><td colSpan={6}><Empty label="No Fuze Audit Log records found."/></td></tr>}</tbody></table></Card>}
  </div>;
}
