"use client";
import { useEffect, useState } from "react";
import StatusChip from "@/components/StatusChip";
type Any = Record<string, any>;
const money = (v?: number) => `R ${Number(v || 0).toLocaleString("en-ZA", { maximumFractionDigits: 0 })}`;
const dateOnly = (v?: string) => (v ? String(v).slice(0, 10) : "—");
export default function PaymentsClient({ payments }: { payments: Any[] }) {
  const [proofs, setProofs] = useState<Any[]>([]);
  const [form, setForm] = useState({ invoice: "", amount: "", reference_number: "" });
  const [file, setFile] = useState<File | null>(null);
  const [busy, setBusy] = useState(false);
  async function loadProofs() { const r = await fetch("/api/payments/proofs"); setProofs(r.ok ? await r.json() : []); }
  useEffect(() => { loadProofs(); }, []);
  async function fileToBase64(input: File | null) { if (!input) return {}; return new Promise<{ filename: string; filedata: string }>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve({ filename: input.name, filedata: String(reader.result) }); reader.onerror = reject; reader.readAsDataURL(input); }); }
  async function submitProof(e: React.FormEvent) { e.preventDefault(); setBusy(true); const attachment = await fileToBase64(file); await fetch("/api/payments/proofs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, amount: Number(form.amount), ...attachment }) }); setForm({ invoice: "", amount: "", reference_number: "" }); setFile(null); await loadProofs(); setBusy(false); }
  async function approve(proof: Any) { await fetch(`/api/payments/proofs/${encodeURIComponent(proof.name)}/approve`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ invoice: proof.invoice || proof.sales_invoice, amount: proof.amount, reference_number: proof.reference_number }) }); await loadProofs(); }
  async function reject(proof: Any) { await fetch(`/api/payments/proofs/${encodeURIComponent(proof.name)}/reject`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reason: "Rejected from portal" }) }); await loadProofs(); }
  return <div><div className="page-head"><div><h1 className="page-title">Payments</h1><div className="page-sub">Payment entries, bank transfer proof uploads and admin approval workflow.</div></div></div><div className="two-col"><div className="card"><div className="card-head"><h3>Upload Proof of Payment</h3></div><div className="card-body"><form onSubmit={submitProof}><div className="field"><label>Sales Invoice</label><input value={form.invoice} onChange={(e)=>setForm({ ...form, invoice: e.target.value })} placeholder="ACC-SINV-2026-00001" required /></div><div className="field-row"><div className="field"><label>Amount Paid</label><input type="number" value={form.amount} onChange={(e)=>setForm({ ...form, amount: e.target.value })} required /></div><div className="field"><label>Bank Reference</label><input value={form.reference_number} onChange={(e)=>setForm({ ...form, reference_number: e.target.value })} required /></div></div><div className="field"><label>Proof File</label><input type="file" accept="image/*,.pdf" onChange={(e)=>setFile(e.target.files?.[0] || null)} /></div><button className="btn btn-primary" disabled={busy}>{busy ? "Submitting…" : "Submit POP"}</button></form></div></div><div className="card"><div className="card-head"><h3>POP Approval Queue</h3></div><div className="card-body"><table className="data"><thead><tr><th>Proof</th><th>Invoice</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{proofs.slice(0,20).map((p)=><tr key={p.name}><td>{p.name}</td><td>{p.invoice || p.sales_invoice}</td><td>{money(p.amount)}</td><td><StatusChip status={p.status}/></td><td><div className="row"><button className="btn btn-sm" onClick={()=>approve(p)}>Approve</button><button className="btn btn-sm" onClick={()=>reject(p)}>Reject</button></div></td></tr>)}{proofs.length === 0 && <tr><td colSpan={5}><div className="empty">No proof of payment records.</div></td></tr>}</tbody></table></div></div></div><div className="card mt"><div className="card-head"><h3>Business Suite Payment Entries</h3></div><div className="card-body"><table className="data"><thead><tr><th>Payment</th><th>Party</th><th>Date</th><th>Amount</th><th>Type</th><th>Status</th></tr></thead><tbody>{payments.map((r)=><tr key={r.name}><td>{r.name}</td><td>{r.party}</td><td>{dateOnly(r.posting_date)}</td><td>{money(r.paid_amount)}</td><td>{r.payment_type}</td><td><StatusChip status={r.status}/></td></tr>)}</tbody></table></div></div></div>;
}
