"use client";
import { useMemo, useState } from "react";
import StatusChip from "@/components/StatusChip";

type Row = Record<string, unknown>;
const LEAD_STAGES = ["Lead", "Open", "Replied", "Opportunity", "Quotation", "Converted", "Lost"];
const OPP_STAGES = ["Open", "Quotation", "Converted", "Lost", "Closed"];
function money(value: unknown) { return Number(value || 0).toLocaleString("en-ZA", { style: "currency", currency: "ZAR" }); }
function title(row: Row, kind: "lead" | "opportunity") { return String(kind === "lead" ? (row.lead_name || row.company_name || row.name) : (row.party_name || row.name)); }
function getStage(row: Row, mode: "leads" | "opportunities") { return String(row.status || (mode === "leads" ? "Lead" : "Open")); }
export default function CrmPipelineClient({ initialLeads, initialOpportunities }: { initialLeads: Row[]; initialOpportunities: Row[] }) {
  const [leads, setLeads] = useState<Row[]>(initialLeads || []); const [opps, setOpps] = useState<Row[]>(initialOpportunities || []);
  const [mode, setMode] = useState<"leads" | "opportunities">("opportunities"); const [query, setQuery] = useState(""); const [selectedStage, setSelectedStage] = useState("");
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState("");
  const stages = mode === "leads" ? LEAD_STAGES : OPP_STAGES; const rows = mode === "leads" ? leads : opps;
  const searchFiltered = useMemo(() => { const q = query.toLowerCase().trim(); return q ? rows.filter((r) => Object.values(r).some((v) => String(v ?? "").toLowerCase().includes(q))) : rows; }, [rows, query]);
  const filtered = useMemo(() => selectedStage ? searchFiltered.filter((r) => getStage(r, mode) === selectedStage) : searchFiltered, [searchFiltered, selectedStage, mode]);
  const totals = useMemo(() => ({ leads: leads.length, opportunities: opps.length, value: opps.reduce((s, r) => s + Number(r.opportunity_amount || 0), 0) }), [leads, opps]);
  const stageStats = useMemo(() => stages.map((stage) => { const stageRows = searchFiltered.filter((r) => getStage(r, mode) === stage); return { stage, count: stageRows.length, value: stageRows.reduce((s, r) => s + Number(r.opportunity_amount || 0), 0) }; }), [stages, searchFiltered, mode]);
  async function move(row: Row, status: string) { const name = String(row.name || ""); if (!name) return; setSaving(name); setMessage(""); try { const res = await fetch("/api/crm/pipeline", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: mode === "leads" ? "lead" : "opportunity", name, status }) }); const json = await res.json().catch(() => ({})); if (!res.ok) throw new Error(json.error || "Could not update stage"); const updater = (current: Row[]) => current.map((r) => r.name === name ? { ...r, status } : r); if (mode === "leads") setLeads(updater); else setOpps(updater); setMessage("Pipeline updated"); } catch (err) { setMessage(err instanceof Error ? err.message : "Could not update pipeline"); } finally { setSaving(""); } }
  function switchMode(next: "leads" | "opportunities") { setMode(next); setSelectedStage(""); }
  return <div>
    <div className="page-head"><div><h1 className="page-title">Sales & CRM Pipeline</h1><div className="page-sub">Clickable stage cards show leads and opportunities by process status.</div></div><div className="row"><a className="btn" href="/portal/crm?tab=leads">+ Add Lead</a><a className="btn btn-primary" href="/portal/crm?tab=opportunities">+ Add Opportunity</a></div></div>
    {message && <div className="banner info">{message}</div>}
    <div className="kpi-grid"><button type="button" className="kpi text-left" onClick={() => switchMode("leads")}><div className="label">Leads</div><div className="val">{totals.leads}</div><div className="hint">Click to view lead stages</div></button><button type="button" className="kpi teal text-left" onClick={() => switchMode("opportunities")}><div className="label">Opportunities</div><div className="val">{totals.opportunities}</div><div className="hint">Click to view opportunity stages</div></button><div className="kpi warn"><div className="label">Pipeline Value</div><div className="val">{money(totals.value)}</div><div className="hint">Opportunity value</div></div><div className="kpi purple"><div className="label">Current View</div><div className="val">{mode === "leads" ? "Leads" : "Deals"}</div><div className="hint">{selectedStage || "All stages"}</div></div></div>
    <div className="card card-pad" style={{ marginBottom: 16 }}><div className="toolbar"><div className="seg"><button className={mode === "opportunities" ? "on" : ""} onClick={() => switchMode("opportunities")}>Opportunities</button><button className={mode === "leads" ? "on" : ""} onClick={() => switchMode("leads")}>Leads</button></div><div className="search"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search pipeline..." /></div></div></div>
    <div className="kpi-grid" style={{ marginBottom: 16 }}>{stageStats.map((s) => <button key={s.stage} type="button" onClick={() => setSelectedStage(selectedStage === s.stage ? "" : s.stage)} className={`kpi text-left ${selectedStage === s.stage ? "teal" : ""}`}><div className="label">{s.stage}</div><div className="val">{s.count}</div><div className="hint">{mode === "opportunities" ? money(s.value) : "Click to filter list"}</div></button>)}</div>
    {selectedStage ? <div className="banner info">Showing {filtered.length} records in <strong>{selectedStage}</strong>. <button className="btn btn-sm" onClick={() => setSelectedStage("")}>Clear filter</button></div> : null}
    <div className="kanban">{stages.map((stage) => { const stageRows = searchFiltered.filter((r) => getStage(r, mode) === stage); return <div className={`kan-col ${selectedStage === stage ? "ring-2 ring-emerald-200" : ""}`} key={stage}><button type="button" className="w-full text-left" onClick={() => setSelectedStage(selectedStage === stage ? "" : stage)}><h4>{stage}<span className="cnt">{stageRows.length}</span></h4></button>{stageRows.map((row) => <div className="kan-card" key={String(row.name)}><div className="ktitle">{title(row, mode === "leads" ? "lead" : "opportunity")}</div><div className="kmeta"><span>{String(row.company_name || row.opportunity_from || "CRM")}</span>{mode === "opportunities" && <strong>{money(row.opportunity_amount)}</strong>}</div><div style={{ marginTop: 10 }}><StatusChip status={stage} /></div><div className="row" style={{ marginTop: 10, flexWrap: "wrap" }}>{stages.filter((s) => s !== stage).slice(0,3).map((next) => <button key={next} className="btn btn-sm" disabled={saving === row.name} onClick={() => move(row, next)}>{next}</button>)}</div></div>)}</div>; })}</div>
    <div className="card card-pad" style={{ marginTop: 16 }}><h3 className="m-0 text-base font-black text-[#15132E]">{selectedStage || "All"} {mode === "leads" ? "Leads" : "Opportunities"}</h3><div className="overflow-x-auto mt-4"><table className="data"><thead><tr><th>Name</th><th>Stage</th><th>Company / Party</th><th>Value</th><th>Updated</th></tr></thead><tbody>{filtered.map((row) => <tr key={String(row.name)}><td>{String(row.name || "—")}</td><td><StatusChip status={getStage(row, mode)} /></td><td>{title(row, mode === "leads" ? "lead" : "opportunity")}</td><td>{mode === "opportunities" ? money(row.opportunity_amount) : "—"}</td><td>{String(row.modified || "—")}</td></tr>)}{filtered.length === 0 ? <tr><td colSpan={5}>No records found for this stage.</td></tr> : null}</tbody></table></div></div>
  </div>;
}
